/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateEventInput = {
  id?: string | null,
  type: string,
  targetTimestamp?: number | null,
  kind?: string | null,
  eventId?: string | null,
  status?: string | null,
  isTest?: boolean | null,
  isCanceled?: boolean | null,
  originTime?: string | null,
  arrivalTime?: string | null,
  tsunamiForecast?: TsunamiForecastTypeInput | null,
  tsunamiObservation?: TsunamiObservationTypeInput | null,
  earthquakeForecast?: EarthquakeTypeInput | null,
  earthquakeObservation?: EarthquakeTypeInput | null,
  intensityForecastMaxInt?: string | null,
  intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
  intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
  intensityObservationMaxInt?: string | null,
  intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
  intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
  intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
  warningComment?: CommentTypeInput | null,
  forecastComment?: CommentTypeInput | null,
  observationComment?: CommentTypeInput | null,
  varComment?: CommentTypeInput | null,
  freeFormComment?: string | null,
};

export type TsunamiForecastTypeInput = {
  areaTsunamiList?: Array< Array< TsunamiAreaTypeInput | null > | null > | null,
  stationTsunamiList?: Array< Array< TsunamiStationTypeInput | null > | null > | null,
};

export type TsunamiAreaTypeInput = {
  code?: string | null,
  name?: string | null,
  levelCode?: string | null,
  firstHeight?: TsunamiFirstHeightTypeInput | null,
  maxHeight?: TsunamiMaxHeightTypeInput | null,
};

export type TsunamiFirstHeightTypeInput = {
  arrivalTime?: string | null,
  condition?: string | null,
  initial?: string | null,
  height?: TsunamiHeightTypeInput | null,
};

export type TsunamiHeightTypeInput = {
  condition?: string | null,
  description?: string | null,
  height?: string | null,
  addInfo?: string | null,
};

export type TsunamiMaxHeightTypeInput = {
  dateTime?: string | null,
  condition?: string | null,
  height?: TsunamiHeightTypeInput | null,
};

export type TsunamiStationTypeInput = {
  code?: string | null,
  name?: string | null,
  area?: TsunamiAreaTypeInput | null,
  levelCode?: string | null,
};

export type TsunamiObservationTypeInput = {
  stationTsunamiList?: Array< Array< TsunamiStationTypeInput | null > | null > | null,
};

export type EarthquakeTypeInput = {
  hypocenterTokyo?: HypocenterTypeInput | null,
  hypocenterJGD?: HypocenterTypeInput | null,
  serial?: string | null,
  isWarning?: boolean | null,
  isEnd?: boolean | null,
  isPlum?: boolean | null,
};

export type HypocenterTypeInput = {
  areaCode?: string | null,
  areaName?: string | null,
  locationTokyo?: Array< string | null > | null,
  locationJGD?: Array< string | null > | null,
  depth?: string | null,
  description?: string | null,
  magnitude?: string | null,
  landOrSea?: string | null,
  travelTimeTable?: Array< TravelTimeTableTypeInput | null > | null,
};

export type TravelTimeTableTypeInput = {
  P?: number | null,
  S?: number | null,
  D?: number | null,
};

export type CommentTypeInput = {
  code?: Array< string | null > | null,
  text?: string | null,
  codeType?: string | null,
};

export type ModelEventConditionInput = {
  type?: ModelStringInput | null,
  targetTimestamp?: ModelIntInput | null,
  kind?: ModelStringInput | null,
  eventId?: ModelIDInput | null,
  status?: ModelStringInput | null,
  isTest?: ModelBooleanInput | null,
  isCanceled?: ModelBooleanInput | null,
  originTime?: ModelStringInput | null,
  arrivalTime?: ModelStringInput | null,
  intensityForecastMaxInt?: ModelStringInput | null,
  intensityForecastAreaIntList?: ModelIDInput | null,
  intensityForecastStationIntList?: ModelIDInput | null,
  intensityObservationMaxInt?: ModelStringInput | null,
  intensityObservationAreaIntList?: ModelIDInput | null,
  intensityObservationCityIntList?: ModelIDInput | null,
  intensityObservationStationIntList?: ModelIDInput | null,
  freeFormComment?: ModelStringInput | null,
  and?: Array< ModelEventConditionInput | null > | null,
  or?: Array< ModelEventConditionInput | null > | null,
  not?: ModelEventConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type Event = {
  __typename: "Event",
  id?: string,
  type?: string,
  targetTimestamp?: number | null,
  kind?: string | null,
  eventId?: string | null,
  status?: string | null,
  isTest?: boolean | null,
  isCanceled?: boolean | null,
  originTime?: string | null,
  arrivalTime?: string | null,
  tsunamiForecast?: TsunamiForecastType,
  tsunamiObservation?: TsunamiObservationType,
  earthquakeForecast?: EarthquakeType,
  earthquakeObservation?: EarthquakeType,
  intensityForecastMaxInt?: string | null,
  intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
  intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
  intensityObservationMaxInt?: string | null,
  intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
  intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
  intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
  warningComment?: CommentType,
  forecastComment?: CommentType,
  observationComment?: CommentType,
  varComment?: CommentType,
  freeFormComment?: string | null,
  createdAt?: string,
  updatedAt?: string,
};

export type TsunamiForecastType = {
  __typename: "TsunamiForecastType",
  areaTsunamiList?:  Array<TsunamiAreaType | null > | null,
  stationTsunamiList?:  Array<TsunamiStationType | null > | null,
};

export type TsunamiAreaType = {
  __typename: "TsunamiAreaType",
  code?: string | null,
  name?: string | null,
  levelCode?: string | null,
  firstHeight?: TsunamiFirstHeightType,
  maxHeight?: TsunamiMaxHeightType,
};

export type TsunamiFirstHeightType = {
  __typename: "TsunamiFirstHeightType",
  arrivalTime?: string | null,
  condition?: string | null,
  initial?: string | null,
  height?: TsunamiHeightType,
};

export type TsunamiHeightType = {
  __typename: "TsunamiHeightType",
  condition?: string | null,
  description?: string | null,
  height?: string | null,
  addInfo?: string | null,
};

export type TsunamiMaxHeightType = {
  __typename: "TsunamiMaxHeightType",
  dateTime?: string | null,
  condition?: string | null,
  height?: TsunamiHeightType,
};

export type TsunamiStationType = {
  __typename: "TsunamiStationType",
  code?: string | null,
  name?: string | null,
  area?: TsunamiAreaType,
  levelCode?: string | null,
};

export type TsunamiObservationType = {
  __typename: "TsunamiObservationType",
  stationTsunamiList?:  Array<TsunamiStationType | null > | null,
};

export type EarthquakeType = {
  __typename: "EarthquakeType",
  hypocenterTokyo?: HypocenterType,
  hypocenterJGD?: HypocenterType,
  serial?: string | null,
  isWarning?: boolean | null,
  isEnd?: boolean | null,
  isPlum?: boolean | null,
};

export type HypocenterType = {
  __typename: "HypocenterType",
  areaCode?: string | null,
  areaName?: string | null,
  locationTokyo?: Array< string | null > | null,
  locationJGD?: Array< string | null > | null,
  depth?: string | null,
  description?: string | null,
  magnitude?: string | null,
  landOrSea?: string | null,
  travelTimeTable?:  Array<TravelTimeTableType | null > | null,
};

export type TravelTimeTableType = {
  __typename: "TravelTimeTableType",
  P?: number | null,
  S?: number | null,
  D?: number | null,
};

export type CommentType = {
  __typename: "CommentType",
  code?: Array< string | null > | null,
  text?: string | null,
  codeType?: string | null,
};

export type UpdateEventInput = {
  id: string,
  type?: string | null,
  targetTimestamp?: number | null,
  kind?: string | null,
  eventId?: string | null,
  status?: string | null,
  isTest?: boolean | null,
  isCanceled?: boolean | null,
  originTime?: string | null,
  arrivalTime?: string | null,
  tsunamiForecast?: TsunamiForecastTypeInput | null,
  tsunamiObservation?: TsunamiObservationTypeInput | null,
  earthquakeForecast?: EarthquakeTypeInput | null,
  earthquakeObservation?: EarthquakeTypeInput | null,
  intensityForecastMaxInt?: string | null,
  intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
  intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
  intensityObservationMaxInt?: string | null,
  intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
  intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
  intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
  warningComment?: CommentTypeInput | null,
  forecastComment?: CommentTypeInput | null,
  observationComment?: CommentTypeInput | null,
  varComment?: CommentTypeInput | null,
  freeFormComment?: string | null,
};

export type DeleteEventInput = {
  id?: string | null,
};

export type ModelEventFilterInput = {
  id?: ModelIDInput | null,
  type?: ModelStringInput | null,
  targetTimestamp?: ModelIntInput | null,
  kind?: ModelStringInput | null,
  eventId?: ModelIDInput | null,
  status?: ModelStringInput | null,
  isTest?: ModelBooleanInput | null,
  isCanceled?: ModelBooleanInput | null,
  originTime?: ModelStringInput | null,
  arrivalTime?: ModelStringInput | null,
  intensityForecastMaxInt?: ModelStringInput | null,
  intensityForecastAreaIntList?: ModelIDInput | null,
  intensityForecastStationIntList?: ModelIDInput | null,
  intensityObservationMaxInt?: ModelStringInput | null,
  intensityObservationAreaIntList?: ModelIDInput | null,
  intensityObservationCityIntList?: ModelIDInput | null,
  intensityObservationStationIntList?: ModelIDInput | null,
  freeFormComment?: ModelStringInput | null,
  and?: Array< ModelEventFilterInput | null > | null,
  or?: Array< ModelEventFilterInput | null > | null,
  not?: ModelEventFilterInput | null,
};

export type ModelEventConnection = {
  __typename: "ModelEventConnection",
  items?:  Array<Event | null > | null,
  nextToken?: string | null,
};

export type ModelIntKeyConditionInput = {
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type CreateEventMutationVariables = {
  input?: CreateEventInput,
  condition?: ModelEventConditionInput | null,
};

export type CreateEventMutation = {
  createEvent?:  {
    __typename: "Event",
    id: string,
    type: string,
    targetTimestamp?: number | null,
    kind?: string | null,
    eventId?: string | null,
    status?: string | null,
    isTest?: boolean | null,
    isCanceled?: boolean | null,
    originTime?: string | null,
    arrivalTime?: string | null,
    tsunamiForecast?:  {
      __typename: "TsunamiForecastType",
      areaTsunamiList?:  Array< {
        __typename: "TsunamiAreaType",
        code?: string | null,
        name?: string | null,
        levelCode?: string | null,
        firstHeight?:  {
          __typename: "TsunamiFirstHeightType",
          arrivalTime?: string | null,
          condition?: string | null,
          initial?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
        maxHeight?:  {
          __typename: "TsunamiMaxHeightType",
          dateTime?: string | null,
          condition?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
      } | null > | null,
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    tsunamiObservation?:  {
      __typename: "TsunamiObservationType",
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    earthquakeForecast?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    earthquakeObservation?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    intensityForecastMaxInt?: string | null,
    intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
    intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
    intensityObservationMaxInt?: string | null,
    intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
    intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
    intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
    warningComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    forecastComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    observationComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    varComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    freeFormComment?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateEventMutationVariables = {
  input?: UpdateEventInput,
  condition?: ModelEventConditionInput | null,
};

export type UpdateEventMutation = {
  updateEvent?:  {
    __typename: "Event",
    id: string,
    type: string,
    targetTimestamp?: number | null,
    kind?: string | null,
    eventId?: string | null,
    status?: string | null,
    isTest?: boolean | null,
    isCanceled?: boolean | null,
    originTime?: string | null,
    arrivalTime?: string | null,
    tsunamiForecast?:  {
      __typename: "TsunamiForecastType",
      areaTsunamiList?:  Array< {
        __typename: "TsunamiAreaType",
        code?: string | null,
        name?: string | null,
        levelCode?: string | null,
        firstHeight?:  {
          __typename: "TsunamiFirstHeightType",
          arrivalTime?: string | null,
          condition?: string | null,
          initial?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
        maxHeight?:  {
          __typename: "TsunamiMaxHeightType",
          dateTime?: string | null,
          condition?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
      } | null > | null,
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    tsunamiObservation?:  {
      __typename: "TsunamiObservationType",
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    earthquakeForecast?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    earthquakeObservation?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    intensityForecastMaxInt?: string | null,
    intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
    intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
    intensityObservationMaxInt?: string | null,
    intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
    intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
    intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
    warningComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    forecastComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    observationComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    varComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    freeFormComment?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteEventMutationVariables = {
  input?: DeleteEventInput,
  condition?: ModelEventConditionInput | null,
};

export type DeleteEventMutation = {
  deleteEvent?:  {
    __typename: "Event",
    id: string,
    type: string,
    targetTimestamp?: number | null,
    kind?: string | null,
    eventId?: string | null,
    status?: string | null,
    isTest?: boolean | null,
    isCanceled?: boolean | null,
    originTime?: string | null,
    arrivalTime?: string | null,
    tsunamiForecast?:  {
      __typename: "TsunamiForecastType",
      areaTsunamiList?:  Array< {
        __typename: "TsunamiAreaType",
        code?: string | null,
        name?: string | null,
        levelCode?: string | null,
        firstHeight?:  {
          __typename: "TsunamiFirstHeightType",
          arrivalTime?: string | null,
          condition?: string | null,
          initial?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
        maxHeight?:  {
          __typename: "TsunamiMaxHeightType",
          dateTime?: string | null,
          condition?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
      } | null > | null,
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    tsunamiObservation?:  {
      __typename: "TsunamiObservationType",
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    earthquakeForecast?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    earthquakeObservation?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    intensityForecastMaxInt?: string | null,
    intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
    intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
    intensityObservationMaxInt?: string | null,
    intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
    intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
    intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
    warningComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    forecastComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    observationComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    varComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    freeFormComment?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetEventQueryVariables = {
  id?: string,
};

export type GetEventQuery = {
  getEvent?:  {
    __typename: "Event",
    id: string,
    type: string,
    targetTimestamp?: number | null,
    kind?: string | null,
    eventId?: string | null,
    status?: string | null,
    isTest?: boolean | null,
    isCanceled?: boolean | null,
    originTime?: string | null,
    arrivalTime?: string | null,
    tsunamiForecast?:  {
      __typename: "TsunamiForecastType",
      areaTsunamiList?:  Array< {
        __typename: "TsunamiAreaType",
        code?: string | null,
        name?: string | null,
        levelCode?: string | null,
        firstHeight?:  {
          __typename: "TsunamiFirstHeightType",
          arrivalTime?: string | null,
          condition?: string | null,
          initial?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
        maxHeight?:  {
          __typename: "TsunamiMaxHeightType",
          dateTime?: string | null,
          condition?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
      } | null > | null,
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    tsunamiObservation?:  {
      __typename: "TsunamiObservationType",
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    earthquakeForecast?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    earthquakeObservation?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    intensityForecastMaxInt?: string | null,
    intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
    intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
    intensityObservationMaxInt?: string | null,
    intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
    intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
    intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
    warningComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    forecastComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    observationComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    varComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    freeFormComment?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListEventsQueryVariables = {
  filter?: ModelEventFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListEventsQuery = {
  listEvents?:  {
    __typename: "ModelEventConnection",
    items?:  Array< {
      __typename: "Event",
      id: string,
      type: string,
      targetTimestamp?: number | null,
      kind?: string | null,
      eventId?: string | null,
      status?: string | null,
      isTest?: boolean | null,
      isCanceled?: boolean | null,
      originTime?: string | null,
      arrivalTime?: string | null,
      tsunamiForecast?:  {
        __typename: "TsunamiForecastType",
        areaTsunamiList?:  Array< {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null > | null,
        stationTsunamiList?:  Array< {
          __typename: "TsunamiStationType",
          code?: string | null,
          name?: string | null,
          area?:  {
            __typename: "TsunamiAreaType",
            code?: string | null,
            name?: string | null,
            levelCode?: string | null,
            firstHeight?:  {
              __typename: "TsunamiFirstHeightType",
              arrivalTime?: string | null,
              condition?: string | null,
              initial?: string | null,
              height?:  {
                __typename: "TsunamiHeightType",
                condition?: string | null,
                description?: string | null,
                height?: string | null,
                addInfo?: string | null,
              } | null,
            } | null,
            maxHeight?:  {
              __typename: "TsunamiMaxHeightType",
              dateTime?: string | null,
              condition?: string | null,
              height?:  {
                __typename: "TsunamiHeightType",
                condition?: string | null,
                description?: string | null,
                height?: string | null,
                addInfo?: string | null,
              } | null,
            } | null,
          } | null,
          levelCode?: string | null,
        } | null > | null,
      } | null,
      tsunamiObservation?:  {
        __typename: "TsunamiObservationType",
        stationTsunamiList?:  Array< {
          __typename: "TsunamiStationType",
          code?: string | null,
          name?: string | null,
          area?:  {
            __typename: "TsunamiAreaType",
            code?: string | null,
            name?: string | null,
            levelCode?: string | null,
            firstHeight?:  {
              __typename: "TsunamiFirstHeightType",
              arrivalTime?: string | null,
              condition?: string | null,
              initial?: string | null,
              height?:  {
                __typename: "TsunamiHeightType",
                condition?: string | null,
                description?: string | null,
                height?: string | null,
                addInfo?: string | null,
              } | null,
            } | null,
            maxHeight?:  {
              __typename: "TsunamiMaxHeightType",
              dateTime?: string | null,
              condition?: string | null,
              height?:  {
                __typename: "TsunamiHeightType",
                condition?: string | null,
                description?: string | null,
                height?: string | null,
                addInfo?: string | null,
              } | null,
            } | null,
          } | null,
          levelCode?: string | null,
        } | null > | null,
      } | null,
      earthquakeForecast?:  {
        __typename: "EarthquakeType",
        hypocenterTokyo?:  {
          __typename: "HypocenterType",
          areaCode?: string | null,
          areaName?: string | null,
          locationTokyo?: Array< string | null > | null,
          locationJGD?: Array< string | null > | null,
          depth?: string | null,
          description?: string | null,
          magnitude?: string | null,
          landOrSea?: string | null,
          travelTimeTable?:  Array< {
            __typename: "TravelTimeTableType",
            P?: number | null,
            S?: number | null,
            D?: number | null,
          } | null > | null,
        } | null,
        hypocenterJGD?:  {
          __typename: "HypocenterType",
          areaCode?: string | null,
          areaName?: string | null,
          locationTokyo?: Array< string | null > | null,
          locationJGD?: Array< string | null > | null,
          depth?: string | null,
          description?: string | null,
          magnitude?: string | null,
          landOrSea?: string | null,
          travelTimeTable?:  Array< {
            __typename: "TravelTimeTableType",
            P?: number | null,
            S?: number | null,
            D?: number | null,
          } | null > | null,
        } | null,
        serial?: string | null,
        isWarning?: boolean | null,
        isEnd?: boolean | null,
        isPlum?: boolean | null,
      } | null,
      earthquakeObservation?:  {
        __typename: "EarthquakeType",
        hypocenterTokyo?:  {
          __typename: "HypocenterType",
          areaCode?: string | null,
          areaName?: string | null,
          locationTokyo?: Array< string | null > | null,
          locationJGD?: Array< string | null > | null,
          depth?: string | null,
          description?: string | null,
          magnitude?: string | null,
          landOrSea?: string | null,
          travelTimeTable?:  Array< {
            __typename: "TravelTimeTableType",
            P?: number | null,
            S?: number | null,
            D?: number | null,
          } | null > | null,
        } | null,
        hypocenterJGD?:  {
          __typename: "HypocenterType",
          areaCode?: string | null,
          areaName?: string | null,
          locationTokyo?: Array< string | null > | null,
          locationJGD?: Array< string | null > | null,
          depth?: string | null,
          description?: string | null,
          magnitude?: string | null,
          landOrSea?: string | null,
          travelTimeTable?:  Array< {
            __typename: "TravelTimeTableType",
            P?: number | null,
            S?: number | null,
            D?: number | null,
          } | null > | null,
        } | null,
        serial?: string | null,
        isWarning?: boolean | null,
        isEnd?: boolean | null,
        isPlum?: boolean | null,
      } | null,
      intensityForecastMaxInt?: string | null,
      intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
      intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
      intensityObservationMaxInt?: string | null,
      intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
      intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
      intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
      warningComment?:  {
        __typename: "CommentType",
        code?: Array< string | null > | null,
        text?: string | null,
        codeType?: string | null,
      } | null,
      forecastComment?:  {
        __typename: "CommentType",
        code?: Array< string | null > | null,
        text?: string | null,
        codeType?: string | null,
      } | null,
      observationComment?:  {
        __typename: "CommentType",
        code?: Array< string | null > | null,
        text?: string | null,
        codeType?: string | null,
      } | null,
      varComment?:  {
        __typename: "CommentType",
        code?: Array< string | null > | null,
        text?: string | null,
        codeType?: string | null,
      } | null,
      freeFormComment?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type ListEventsSortedByTargetTimestampQueryVariables = {
  type?: string | null,
  targetTimestamp?: ModelIntKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelEventFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListEventsSortedByTargetTimestampQuery = {
  listEventsSortedByTargetTimestamp?:  {
    __typename: "ModelEventConnection",
    items?:  Array< {
      __typename: "Event",
      id: string,
      type: string,
      targetTimestamp?: number | null,
      kind?: string | null,
      eventId?: string | null,
      status?: string | null,
      isTest?: boolean | null,
      isCanceled?: boolean | null,
      originTime?: string | null,
      arrivalTime?: string | null,
      tsunamiForecast?:  {
        __typename: "TsunamiForecastType",
        areaTsunamiList?:  Array< {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null > | null,
        stationTsunamiList?:  Array< {
          __typename: "TsunamiStationType",
          code?: string | null,
          name?: string | null,
          area?:  {
            __typename: "TsunamiAreaType",
            code?: string | null,
            name?: string | null,
            levelCode?: string | null,
            firstHeight?:  {
              __typename: "TsunamiFirstHeightType",
              arrivalTime?: string | null,
              condition?: string | null,
              initial?: string | null,
              height?:  {
                __typename: "TsunamiHeightType",
                condition?: string | null,
                description?: string | null,
                height?: string | null,
                addInfo?: string | null,
              } | null,
            } | null,
            maxHeight?:  {
              __typename: "TsunamiMaxHeightType",
              dateTime?: string | null,
              condition?: string | null,
              height?:  {
                __typename: "TsunamiHeightType",
                condition?: string | null,
                description?: string | null,
                height?: string | null,
                addInfo?: string | null,
              } | null,
            } | null,
          } | null,
          levelCode?: string | null,
        } | null > | null,
      } | null,
      tsunamiObservation?:  {
        __typename: "TsunamiObservationType",
        stationTsunamiList?:  Array< {
          __typename: "TsunamiStationType",
          code?: string | null,
          name?: string | null,
          area?:  {
            __typename: "TsunamiAreaType",
            code?: string | null,
            name?: string | null,
            levelCode?: string | null,
            firstHeight?:  {
              __typename: "TsunamiFirstHeightType",
              arrivalTime?: string | null,
              condition?: string | null,
              initial?: string | null,
              height?:  {
                __typename: "TsunamiHeightType",
                condition?: string | null,
                description?: string | null,
                height?: string | null,
                addInfo?: string | null,
              } | null,
            } | null,
            maxHeight?:  {
              __typename: "TsunamiMaxHeightType",
              dateTime?: string | null,
              condition?: string | null,
              height?:  {
                __typename: "TsunamiHeightType",
                condition?: string | null,
                description?: string | null,
                height?: string | null,
                addInfo?: string | null,
              } | null,
            } | null,
          } | null,
          levelCode?: string | null,
        } | null > | null,
      } | null,
      earthquakeForecast?:  {
        __typename: "EarthquakeType",
        hypocenterTokyo?:  {
          __typename: "HypocenterType",
          areaCode?: string | null,
          areaName?: string | null,
          locationTokyo?: Array< string | null > | null,
          locationJGD?: Array< string | null > | null,
          depth?: string | null,
          description?: string | null,
          magnitude?: string | null,
          landOrSea?: string | null,
          travelTimeTable?:  Array< {
            __typename: "TravelTimeTableType",
            P?: number | null,
            S?: number | null,
            D?: number | null,
          } | null > | null,
        } | null,
        hypocenterJGD?:  {
          __typename: "HypocenterType",
          areaCode?: string | null,
          areaName?: string | null,
          locationTokyo?: Array< string | null > | null,
          locationJGD?: Array< string | null > | null,
          depth?: string | null,
          description?: string | null,
          magnitude?: string | null,
          landOrSea?: string | null,
          travelTimeTable?:  Array< {
            __typename: "TravelTimeTableType",
            P?: number | null,
            S?: number | null,
            D?: number | null,
          } | null > | null,
        } | null,
        serial?: string | null,
        isWarning?: boolean | null,
        isEnd?: boolean | null,
        isPlum?: boolean | null,
      } | null,
      earthquakeObservation?:  {
        __typename: "EarthquakeType",
        hypocenterTokyo?:  {
          __typename: "HypocenterType",
          areaCode?: string | null,
          areaName?: string | null,
          locationTokyo?: Array< string | null > | null,
          locationJGD?: Array< string | null > | null,
          depth?: string | null,
          description?: string | null,
          magnitude?: string | null,
          landOrSea?: string | null,
          travelTimeTable?:  Array< {
            __typename: "TravelTimeTableType",
            P?: number | null,
            S?: number | null,
            D?: number | null,
          } | null > | null,
        } | null,
        hypocenterJGD?:  {
          __typename: "HypocenterType",
          areaCode?: string | null,
          areaName?: string | null,
          locationTokyo?: Array< string | null > | null,
          locationJGD?: Array< string | null > | null,
          depth?: string | null,
          description?: string | null,
          magnitude?: string | null,
          landOrSea?: string | null,
          travelTimeTable?:  Array< {
            __typename: "TravelTimeTableType",
            P?: number | null,
            S?: number | null,
            D?: number | null,
          } | null > | null,
        } | null,
        serial?: string | null,
        isWarning?: boolean | null,
        isEnd?: boolean | null,
        isPlum?: boolean | null,
      } | null,
      intensityForecastMaxInt?: string | null,
      intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
      intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
      intensityObservationMaxInt?: string | null,
      intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
      intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
      intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
      warningComment?:  {
        __typename: "CommentType",
        code?: Array< string | null > | null,
        text?: string | null,
        codeType?: string | null,
      } | null,
      forecastComment?:  {
        __typename: "CommentType",
        code?: Array< string | null > | null,
        text?: string | null,
        codeType?: string | null,
      } | null,
      observationComment?:  {
        __typename: "CommentType",
        code?: Array< string | null > | null,
        text?: string | null,
        codeType?: string | null,
      } | null,
      varComment?:  {
        __typename: "CommentType",
        code?: Array< string | null > | null,
        text?: string | null,
        codeType?: string | null,
      } | null,
      freeFormComment?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type OnMutateEventSubscription = {
  onMutateEvent?:  {
    __typename: "Event",
    id: string,
    type: string,
    targetTimestamp?: number | null,
    kind?: string | null,
    eventId?: string | null,
    status?: string | null,
    isTest?: boolean | null,
    isCanceled?: boolean | null,
    originTime?: string | null,
    arrivalTime?: string | null,
    tsunamiForecast?:  {
      __typename: "TsunamiForecastType",
      areaTsunamiList?:  Array< {
        __typename: "TsunamiAreaType",
        code?: string | null,
        name?: string | null,
        levelCode?: string | null,
        firstHeight?:  {
          __typename: "TsunamiFirstHeightType",
          arrivalTime?: string | null,
          condition?: string | null,
          initial?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
        maxHeight?:  {
          __typename: "TsunamiMaxHeightType",
          dateTime?: string | null,
          condition?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
      } | null > | null,
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    tsunamiObservation?:  {
      __typename: "TsunamiObservationType",
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    earthquakeForecast?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    earthquakeObservation?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    intensityForecastMaxInt?: string | null,
    intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
    intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
    intensityObservationMaxInt?: string | null,
    intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
    intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
    intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
    warningComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    forecastComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    observationComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    varComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    freeFormComment?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateEventSubscription = {
  onCreateEvent?:  {
    __typename: "Event",
    id: string,
    type: string,
    targetTimestamp?: number | null,
    kind?: string | null,
    eventId?: string | null,
    status?: string | null,
    isTest?: boolean | null,
    isCanceled?: boolean | null,
    originTime?: string | null,
    arrivalTime?: string | null,
    tsunamiForecast?:  {
      __typename: "TsunamiForecastType",
      areaTsunamiList?:  Array< {
        __typename: "TsunamiAreaType",
        code?: string | null,
        name?: string | null,
        levelCode?: string | null,
        firstHeight?:  {
          __typename: "TsunamiFirstHeightType",
          arrivalTime?: string | null,
          condition?: string | null,
          initial?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
        maxHeight?:  {
          __typename: "TsunamiMaxHeightType",
          dateTime?: string | null,
          condition?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
      } | null > | null,
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    tsunamiObservation?:  {
      __typename: "TsunamiObservationType",
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    earthquakeForecast?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    earthquakeObservation?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    intensityForecastMaxInt?: string | null,
    intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
    intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
    intensityObservationMaxInt?: string | null,
    intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
    intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
    intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
    warningComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    forecastComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    observationComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    varComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    freeFormComment?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateEventSubscription = {
  onUpdateEvent?:  {
    __typename: "Event",
    id: string,
    type: string,
    targetTimestamp?: number | null,
    kind?: string | null,
    eventId?: string | null,
    status?: string | null,
    isTest?: boolean | null,
    isCanceled?: boolean | null,
    originTime?: string | null,
    arrivalTime?: string | null,
    tsunamiForecast?:  {
      __typename: "TsunamiForecastType",
      areaTsunamiList?:  Array< {
        __typename: "TsunamiAreaType",
        code?: string | null,
        name?: string | null,
        levelCode?: string | null,
        firstHeight?:  {
          __typename: "TsunamiFirstHeightType",
          arrivalTime?: string | null,
          condition?: string | null,
          initial?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
        maxHeight?:  {
          __typename: "TsunamiMaxHeightType",
          dateTime?: string | null,
          condition?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
      } | null > | null,
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    tsunamiObservation?:  {
      __typename: "TsunamiObservationType",
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    earthquakeForecast?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    earthquakeObservation?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    intensityForecastMaxInt?: string | null,
    intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
    intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
    intensityObservationMaxInt?: string | null,
    intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
    intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
    intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
    warningComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    forecastComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    observationComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    varComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    freeFormComment?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteEventSubscription = {
  onDeleteEvent?:  {
    __typename: "Event",
    id: string,
    type: string,
    targetTimestamp?: number | null,
    kind?: string | null,
    eventId?: string | null,
    status?: string | null,
    isTest?: boolean | null,
    isCanceled?: boolean | null,
    originTime?: string | null,
    arrivalTime?: string | null,
    tsunamiForecast?:  {
      __typename: "TsunamiForecastType",
      areaTsunamiList?:  Array< {
        __typename: "TsunamiAreaType",
        code?: string | null,
        name?: string | null,
        levelCode?: string | null,
        firstHeight?:  {
          __typename: "TsunamiFirstHeightType",
          arrivalTime?: string | null,
          condition?: string | null,
          initial?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
        maxHeight?:  {
          __typename: "TsunamiMaxHeightType",
          dateTime?: string | null,
          condition?: string | null,
          height?:  {
            __typename: "TsunamiHeightType",
            condition?: string | null,
            description?: string | null,
            height?: string | null,
            addInfo?: string | null,
          } | null,
        } | null,
      } | null > | null,
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    tsunamiObservation?:  {
      __typename: "TsunamiObservationType",
      stationTsunamiList?:  Array< {
        __typename: "TsunamiStationType",
        code?: string | null,
        name?: string | null,
        area?:  {
          __typename: "TsunamiAreaType",
          code?: string | null,
          name?: string | null,
          levelCode?: string | null,
          firstHeight?:  {
            __typename: "TsunamiFirstHeightType",
            arrivalTime?: string | null,
            condition?: string | null,
            initial?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
          maxHeight?:  {
            __typename: "TsunamiMaxHeightType",
            dateTime?: string | null,
            condition?: string | null,
            height?:  {
              __typename: "TsunamiHeightType",
              condition?: string | null,
              description?: string | null,
              height?: string | null,
              addInfo?: string | null,
            } | null,
          } | null,
        } | null,
        levelCode?: string | null,
      } | null > | null,
    } | null,
    earthquakeForecast?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    earthquakeObservation?:  {
      __typename: "EarthquakeType",
      hypocenterTokyo?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      hypocenterJGD?:  {
        __typename: "HypocenterType",
        areaCode?: string | null,
        areaName?: string | null,
        locationTokyo?: Array< string | null > | null,
        locationJGD?: Array< string | null > | null,
        depth?: string | null,
        description?: string | null,
        magnitude?: string | null,
        landOrSea?: string | null,
        travelTimeTable?:  Array< {
          __typename: "TravelTimeTableType",
          P?: number | null,
          S?: number | null,
          D?: number | null,
        } | null > | null,
      } | null,
      serial?: string | null,
      isWarning?: boolean | null,
      isEnd?: boolean | null,
      isPlum?: boolean | null,
    } | null,
    intensityForecastMaxInt?: string | null,
    intensityForecastAreaIntList?: Array< Array< string | null > | null > | null,
    intensityForecastStationIntList?: Array< Array< string | null > | null > | null,
    intensityObservationMaxInt?: string | null,
    intensityObservationAreaIntList?: Array< Array< string | null > | null > | null,
    intensityObservationCityIntList?: Array< Array< string | null > | null > | null,
    intensityObservationStationIntList?: Array< Array< string | null > | null > | null,
    warningComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    forecastComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    observationComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    varComment?:  {
      __typename: "CommentType",
      code?: Array< string | null > | null,
      text?: string | null,
      codeType?: string | null,
    } | null,
    freeFormComment?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
