/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const dev = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:fbc7d242-939c-4621-a682-50e02ea58f6c",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_VU99iiIxm",
    "aws_user_pools_web_client_id": "4smn3ah18kbub43r7mo9ffgpc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://sdxz5aejg5ds3enb7jhghkmciy.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

const staging = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:fbc7d242-939c-4621-a682-50e02ea58f6c",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_multQWdvb",
    "aws_user_pools_web_client_id": "52i0bstlklqnj5ukj4l55pke6b",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tcd4qp6hubb2vna3ucwhji3zvm.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

const prod = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:fbc7d242-939c-4621-a682-50e02ea58f6c",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_6phTEx1MI",
    "aws_user_pools_web_client_id": "5lmg5lq4oe471usni9tgfgq9pa",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jjb2773a5fadrgyeoxrxpp5l6e.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

const awsmobile = {
    dev,
    staging,
    prod
}

export default awsmobile;
